version: '3.7'

services:
  my-app:
    image: nginx
    volumes:
    - ./www:/usr/share/nginx/html/
    environment:
      VIRTUAL_HOST: my-app.local
      VIRTUAL_PORT: 3000
networks:
  default:
    external:
      name: proxy_nginx-proxy
